---
version: "3"
services:
 devopsdb:
   build: ./Docker-db
   container_name: devopsdb
   ports:
     - "3306:3306"
   volumes:
   - mysqlvolume:/var/lib/mysql
 application:
   build: ./Docker-app
   container_name: appcont
   ports:
     - "1234:8080"
   environment:
     DB_HOST: devopsdb
     DB_PASSWORD: devopspassword
     DB_NAME: accounts
   depends_on:
     - devopsdb
volumes:
  mysqlvolume:

