---
version: "3"
services:
 devopsdb:
   image: saipraveen63/dbimage
   container_name: devopsdb 
   ports:
     - "3306:3306"
 application:
   image: saipraveen63/appimage
   container_name: appcontainer
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
